In [1]:
!pip3 install pandas

list of list

In [5]:
import pandas as pd
l1=[[11,22,33],[44,55,66],[77,88,99]]
df1=pd.DataFrame(l1,index=['r1','r2','r2'],columns=['c1','c2','c3'])
df1

c1  c2  c3
r1  11  22  33
r2  44  55  66
r2  77  88  99

dict of list

In [7]:
dl={'tsla':[200,201,202,203],
    'goog':[500,501,502,503],
    'nvda':[600,601,602,603]}
df2=pd.DataFrame(dl,index=[5,6,7,8])
df2

tsla  goog  nvda
5   200   500   600
6   201   501   601
7   202   502   602
8   203   503   603

list of dict

In [11]:
stock=[
    {"name":'apple' ,'price':300 ,'sector':'tech'},
    {"name":'ongc' ,'price':500 ,'sector':'oil'},
    {"name":'artil' ,'price':400 ,'sector':'oil',}
]
df3=pd.DataFrame(stock,index=[55,66,77])
df3

name  price sector
55  apple    300   tech
66   ongc    500    oil
77  artil    400    oil

numpy array

In [12]:
import numpy as np
import pandas as pd

m1=np.arange(16).reshape(4,4)
print(m1)

df1=pd.DataFrame(m1,index=['r1','r2','r3','r4'],columns=['c1','c2','c3','c4'])
df1

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


c1  c2  c3  c4
r1   0   1   2   3
r2   4   5   6   7
r3   8   9  10  11
r4  12  13  14  15

csv file

In [13]:
import pandas as pd
df3=pd.read_csv(r'/Users/new algo trading/batch32/11_data_analysis/sp500.csv')
df3

Name                  Sector   Price    EPS
0                     Apple Inc  Information Technology  170.12   9.20
1                    Abbvie Inc             Health Care   93.29   5.31
2           Abbott Laboratories             Health Care   55.28   2.41
3                 Accenture Plc  Information Technology  145.30   5.91
4                  Allergan Plc             Health Care  171.81  15.42
..                          ...                     ...     ...    ...
97   Verizon Communications Inc      Telecommunications   45.85   3.75
98     Walgreens Boots Alliance        Consumer Staples   70.25   5.10
99        Wells Fargo & Company              Financials   54.02   4.14
100             Wal-Mart Stores        Consumer Staples   96.08   4.36
101            Exxon Mobil Corp                  Energy   80.31   3.56

[102 rows x 4 columns]

exel

html