In [5]:
import numpy as np
import pandas as pd

m1=np.arange(16).reshape(4,4)
print(m1)

df1=pd.DataFrame(m1,index=['r1','r2','r3','r4'],columns=['c1','c2','c3','c4'])
df1.index.name='i1'
df1

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


c1  c2  c3  c4
i1                
r1   0   1   2   3
r2   4   5   6   7
r3   8   9  10  11
r4  12  13  14  15

In [8]:
m1=np.arange(100,116).reshape(4,4)
print(m1)

df2=pd.DataFrame(m1,index=['r1','r2','r3','r5'],columns=['c5','c6','c7','c8'])
df2.index.name='i1'
df2

[[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]
 [112 113 114 115]]


c5   c6   c7   c8
i1                    
r1  100  101  102  103
r2  104  105  106  107
r3  108  109  110  111
r5  112  113  114  115

In [13]:
pd.merge(df1,df2,on='i1',how='outer')

c1    c2    c3    c4     c5     c6     c7     c8
i1                                                    
r1   0.0   1.0   2.0   3.0  100.0  101.0  102.0  103.0
r2   4.0   5.0   6.0   7.0  104.0  105.0  106.0  107.0
r3   8.0   9.0  10.0  11.0  108.0  109.0  110.0  111.0
r4  12.0  13.0  14.0  15.0    NaN    NaN    NaN    NaN
r5   NaN   NaN   NaN   NaN  112.0  113.0  114.0  115.0

In [15]:
m1=np.arange(100,116).reshape(4,4)
df5=pd.DataFrame(m1,index=['r1','r2','r3','r4'],columns=['c1','c2','c3','c4'])
# df5.index.name='i1'
df5

c1   c2   c3   c4
r1  100  101  102  103
r2  104  105  106  107
r3  108  109  110  111
r4  112  113  114  115

In [22]:

m1=np.arange(16).reshape(4,4)

df6=pd.DataFrame(m1,index=['r5','r6','r7','r8'],columns=['c1','c2','c3','c4'])
# df6.index.name='i1'
df6

c1  c2  c3  c4
r5   0   1   2   3
r6   4   5   6   7
r7   8   9  10  11
r8  12  13  14  15

In [23]:
pd.concat([df5,df6])

c1   c2   c3   c4
r1  100  101  102  103
r2  104  105  106  107
r3  108  109  110  111
r4  112  113  114  115
r5    0    1    2    3
r6    4    5    6    7
r7    8    9   10   11
r8   12   13   14   15

In [26]:
data1=pd.read_html('https://en.wikipedia.org/wiki/Dow_Jones_Industrial_Average')
data1=data1[2]
data1

Company Exchange Symbol                        Industry  \
0                   3M     NYSE    MMM                    Conglomerate   
1     American Express     NYSE    AXP              Financial services   
2                Amgen   NASDAQ   AMGN               Biopharmaceutical   
3               Amazon   NASDAQ   AMZN                       Retailing   
4                Apple   NASDAQ   AAPL          Information technology   
5               Boeing     NYSE     BA           Aerospace and defense   
6          Caterpillar     NYSE    CAT         Construction and mining   
7              Chevron     NYSE    CVX              Petroleum industry   
8                Cisco   NASDAQ   CSCO          Information technology   
9            Coca-Cola     NYSE     KO                  Drink industry   
10              Disney     NYSE    DIS  Broadcasting and entertainment   
11       Goldman Sachs     NYSE     GS              Financial services   
12          Home Depot     NYSE     HD                Home Improvement   
13           Honeywell   NASDAQ    HON                    Conglomerate   
14                 IBM     NYSE    IBM          Information technology   
15   Johnson & Johnson     NYSE    JNJ         Pharmaceutical industry   
16      JPMorgan Chase     NYSE    JPM              Financial services   
17          McDonald's     NYSE    MCD                   Food industry   
18               Merck     NYSE    MRK         Pharmaceutical industry   
19           Microsoft   NASDAQ   MSFT          Information technology   
20                Nike     NYSE    NKE               Clothing industry   
21              Nvidia   NASDAQ   NVDA          Information technology   
22    Procter & Gamble     NYSE     PG      Fast-moving consumer goods   
23          Salesforce     NYSE    CRM          Information technology   
24    Sherwin-Williams     NYSE    SHW             Specialty chemicals   
25           Travelers     NYSE    TRV                       Insurance   
26  UnitedHealth Group     NYSE    UNH             Managed health care   
27             Verizon     NYSE     VZ     Telecommunications industry   
28                Visa     NYSE      V              Financial services   
29             Walmart     NYSE    WMT                       Retailing   

    Date added                                  Notes Index weighting  
0   1976-08-09  As Minnesota Mining and Manufacturing           2.17%  
1   1982-08-30                                    NaN           4.31%  
2   2020-08-31                                    NaN           4.14%  
3   2024-02-26                                    NaN           2.99%  
4   2015-03-19                                    NaN           2.92%  
5   1987-03-12                                    NaN           3.03%  
6   1991-05-06                                    NaN           5.13%  
7   2008-02-19          Also 1930-07-18 to 1999-11-01           2.01%  
8   2009-06-08                                    NaN           0.92%  
9   1987-03-12          Also 1932-05-26 to 1935-11-20           1.04%  
10  1991-05-06                                    NaN           1.63%  
11  2013-09-23                                    NaN           8.79%  
12  1999-11-01                                    NaN           5.35%  
13  2020-08-31             AlliedSignal and Honeywell           3.27%  
14  1979-06-29          Also 1932-05-26 to 1939-03-04           3.77%  
15  1997-03-17                                    NaN           2.24%  
16  1991-05-06                                    NaN           3.83%  
17  1985-10-30                                    NaN           4.57%  
18  1979-06-29                                    NaN           1.11%  
19  1999-11-01                                    NaN           6.69%  
20  2013-09-23                                    NaN           0.90%  
21  2024-11-08                                    NaN           2.02%  
22  1932-05-26                                    NaN           

In [28]:
data2=pd.read_html('https://en.wikipedia.org/wiki/NIFTY_50')
data2=data2[1]
data2

Company name      Symbol  \
0                 Adani Enterprises    ADANIENT   
1                 Adani Ports & SEZ  ADANIPORTS   
2                  Apollo Hospitals  APOLLOHOSP   
3                      Asian Paints  ASIANPAINT   
4                         Axis Bank    AXISBANK   
5                        Bajaj Auto  BAJAJ-AUTO   
6                     Bajaj Finance  BAJFINANCE   
7                     Bajaj Finserv  BAJAJFINSV   
8                Bharat Electronics         BEL   
9                     Bharti Airtel  BHARTIARTL   
10                            Cipla       CIPLA   
11                       Coal India   COALINDIA   
12         Dr. Reddy's Laboratories     DRREDDY   
13                    Eicher Motors   EICHERMOT   
14                          Eternal     ETERNAL   
15                Grasim Industries      GRASIM   
16                          HCLTech     HCLTECH   
17                        HDFC Bank    HDFCBANK   
18                        HDFC Life    HDFCLIFE   
19                    Hero MotoCorp  HEROMOTOCO   
20              Hindalco Industries    HINDALCO   
21               Hindustan Unilever  HINDUNILVR   
22                       ICICI Bank   ICICIBANK   
23                    IndusInd Bank  INDUSINDBK   
24                          Infosys        INFY   
25                              ITC         ITC   
26           Jio Financial Services      JIOFIN   
27                        JSW Steel    JSWSTEEL   
28              Kotak Mahindra Bank   KOTAKBANK   
29                  Larsen & Toubro          LT   
30              Mahindra & Mahindra         M&M   
31                    Maruti Suzuki      MARUTI   
32                     Nestlé India   NESTLEIND   
33                             NTPC        NTPC   
34  Oil and Natural Gas Corporation        ONGC   
35                       Power Grid   POWERGRID   
36              Reliance Industries    RELIANCE   
37       SBI Life Insurance Company     SBILIFE   
38                  Shriram Finance  SHRIRAMFIN   
39              State Bank of India        SBIN   
40                       Sun Pharma   SUNPHARMA   
41        Tata Consultancy Services         TCS   
42           Tata Consumer Products  TATACONSUM   
43                      Tata Motors  TATAMOTORS   
44                       Tata Steel   TATASTEEL   
45                    Tech Mahindra       TECHM   
46                    Titan Company       TITAN   
47                            Trent       TRENT   
48                 UltraTech Cement  ULTRACEMCO   
49                            Wipro       WIPRO   

                        Sector[15]        Date added[16]  
0                  Metals & Mining     30 September 2022  
1                         Services     28 September 2015  
2                       Healthcare         31 March 2022  
3                Consumer Durables      27 April 2012[a]  
4               Financial Services         27 March 2009  
5   Automobile and Auto Components     1 October 2010[b]  
6               Financial Services     29 September 2017  
7               Financial Services          2 April 2018  
8                    Capital Goods     30 September 2024  
9                Telecommunication          1 March 2004  
10                      Healthcare        7 October 1998  
11     Oil, Gas & Consumable Fuels       10 October 2011  
12                      Healthcare     1 October 2010[c]  
13  Automobile and Auto Components          1 April 2016  
14               Consumer Services         28 March 2025  
15          Construction Materials       2 April 2018[d]  
16          Information Technology       28 October 2002  
17              Financial Services         22 April 1996  
18              Financial Services          31 July 2020  
19  Automobile and Auto Components     7 October 1998[e]  
20                 Metals & Mining         22 April 1996  
21      Fast Moving Consumer Goods         22 April 1996  
22              Financial Services       25 January 2002  
23   

rename column name

In [29]:
data2=data2.rename(columns={'Company name':'Company','Sector[15]':"Industry","Date added[16]":"Date added"})
data2

Company      Symbol  \
0                 Adani Enterprises    ADANIENT   
1                 Adani Ports & SEZ  ADANIPORTS   
2                  Apollo Hospitals  APOLLOHOSP   
3                      Asian Paints  ASIANPAINT   
4                         Axis Bank    AXISBANK   
5                        Bajaj Auto  BAJAJ-AUTO   
6                     Bajaj Finance  BAJFINANCE   
7                     Bajaj Finserv  BAJAJFINSV   
8                Bharat Electronics         BEL   
9                     Bharti Airtel  BHARTIARTL   
10                            Cipla       CIPLA   
11                       Coal India   COALINDIA   
12         Dr. Reddy's Laboratories     DRREDDY   
13                    Eicher Motors   EICHERMOT   
14                          Eternal     ETERNAL   
15                Grasim Industries      GRASIM   
16                          HCLTech     HCLTECH   
17                        HDFC Bank    HDFCBANK   
18                        HDFC Life    HDFCLIFE   
19                    Hero MotoCorp  HEROMOTOCO   
20              Hindalco Industries    HINDALCO   
21               Hindustan Unilever  HINDUNILVR   
22                       ICICI Bank   ICICIBANK   
23                    IndusInd Bank  INDUSINDBK   
24                          Infosys        INFY   
25                              ITC         ITC   
26           Jio Financial Services      JIOFIN   
27                        JSW Steel    JSWSTEEL   
28              Kotak Mahindra Bank   KOTAKBANK   
29                  Larsen & Toubro          LT   
30              Mahindra & Mahindra         M&M   
31                    Maruti Suzuki      MARUTI   
32                     Nestlé India   NESTLEIND   
33                             NTPC        NTPC   
34  Oil and Natural Gas Corporation        ONGC   
35                       Power Grid   POWERGRID   
36              Reliance Industries    RELIANCE   
37       SBI Life Insurance Company     SBILIFE   
38                  Shriram Finance  SHRIRAMFIN   
39              State Bank of India        SBIN   
40                       Sun Pharma   SUNPHARMA   
41        Tata Consultancy Services         TCS   
42           Tata Consumer Products  TATACONSUM   
43                      Tata Motors  TATAMOTORS   
44                       Tata Steel   TATASTEEL   
45                    Tech Mahindra       TECHM   
46                    Titan Company       TITAN   
47                            Trent       TRENT   
48                 UltraTech Cement  ULTRACEMCO   
49                            Wipro       WIPRO   

                          Industry            Date added  
0                  Metals & Mining     30 September 2022  
1                         Services     28 September 2015  
2                       Healthcare         31 March 2022  
3                Consumer Durables      27 April 2012[a]  
4               Financial Services         27 March 2009  
5   Automobile and Auto Components     1 October 2010[b]  
6               Financial Services     29 September 2017  
7               Financial Services          2 April 2018  
8                    Capital Goods     30 September 2024  
9                Telecommunication          1 March 2004  
10                      Healthcare        7 October 1998  
11     Oil, Gas & Consumable Fuels       10 October 2011  
12                      Healthcare     1 October 2010[c]  
13  Automobile and Auto Components          1 April 2016  
14               Consumer Services         28 March 2025  
15          Construction Materials       2 April 2018[d]  
16          Information Technology       28 October 2002  
17              Financial Services         22 April 1996  
18              Financial Services          31 July 2020  
19  Automobile and Auto Components     7 October 1998[e]  
20                 Metals & Mining         22 April 1996  
21      Fast Moving Consumer Goods         22 April 1996  
22              Financial Services       25 January 2002  
23        

In [31]:
data1=data1[['Company',	'Symbol'	,'Industry'	,'Date added']]
data1

Company Symbol                        Industry  Date added
0                   3M    MMM                    Conglomerate  1976-08-09
1     American Express    AXP              Financial services  1982-08-30
2                Amgen   AMGN               Biopharmaceutical  2020-08-31
3               Amazon   AMZN                       Retailing  2024-02-26
4                Apple   AAPL          Information technology  2015-03-19
5               Boeing     BA           Aerospace and defense  1987-03-12
6          Caterpillar    CAT         Construction and mining  1991-05-06
7              Chevron    CVX              Petroleum industry  2008-02-19
8                Cisco   CSCO          Information technology  2009-06-08
9            Coca-Cola     KO                  Drink industry  1987-03-12
10              Disney    DIS  Broadcasting and entertainment  1991-05-06
11       Goldman Sachs     GS              Financial services  2013-09-23
12          Home Depot     HD                Home Improvement  1999-11-01
13           Honeywell    HON                    Conglomerate  2020-08-31
14                 IBM    IBM          Information technology  1979-06-29
15   Johnson & Johnson    JNJ         Pharmaceutical industry  1997-03-17
16      JPMorgan Chase    JPM              Financial services  1991-05-06
17          McDonald's    MCD                   Food industry  1985-10-30
18               Merck    MRK         Pharmaceutical industry  1979-06-29
19           Microsoft   MSFT          Information technology  1999-11-01
20                Nike    NKE               Clothing industry  2013-09-23
21              Nvidia   NVDA          Information technology  2024-11-08
22    Procter & Gamble     PG      Fast-moving consumer goods  1932-05-26
23          Salesforce    CRM          Information technology  2020-08-31
24    Sherwin-Williams    SHW             Specialty chemicals  2024-11-08
25           Travelers    TRV                       Insurance  2009-06-08
26  UnitedHealth Group    UNH             Managed health care  2012-09-24
27             Verizon     VZ     Telecommunications industry  2004-04-08
28                Visa      V              Financial services  2013-09-23
29             Walmart    WMT                       Retailing  1997-03-17

In [32]:
pd.concat([data1,data2])

Company      Symbol                Industry            Date added
0                 3M         MMM            Conglomerate            1976-08-09
1   American Express         AXP      Financial services            1982-08-30
2              Amgen        AMGN       Biopharmaceutical            2020-08-31
3             Amazon        AMZN               Retailing            2024-02-26
4              Apple        AAPL  Information technology            2015-03-19
..               ...         ...                     ...                   ...
45     Tech Mahindra       TECHM  Information Technology         28 March 2014
46     Titan Company       TITAN       Consumer Durables          2 April 2018
47             Trent       TRENT       Consumer Services     30 September 2024
48  UltraTech Cement  ULTRACEMCO  Construction Materials     28 September 2012
49             Wipro       WIPRO  Information Technology  27 September 2013[i]

[80 rows x 4 columns]