In [1]:
!pip3 install pandas

list of list

In [5]:
import pandas as pd
l1=[[11,22,33],[44,55,66],[77,88,99]]
df1=pd.DataFrame(l1,index=['r1','r2','r2'],columns=['c1','c2','c3'])
df1

c1  c2  c3
r1  11  22  33
r2  44  55  66
r2  77  88  99

dict of list

In [7]:
dl={'tsla':[200,201,202,203],
    'goog':[500,501,502,503],
    'nvda':[600,601,602,603]}
df2=pd.DataFrame(dl,index=[5,6,7,8])
df2

tsla  goog  nvda
5   200   500   600
6   201   501   601
7   202   502   602
8   203   503   603

list of dict

In [11]:
stock=[
    {"name":'apple' ,'price':300 ,'sector':'tech'},
    {"name":'ongc' ,'price':500 ,'sector':'oil'},
    {"name":'artil' ,'price':400 ,'sector':'oil',}
]
df3=pd.DataFrame(stock,index=[55,66,77])
df3

name  price sector
55  apple    300   tech
66   ongc    500    oil
77  artil    400    oil

numpy array

In [12]:
import numpy as np
import pandas as pd

m1=np.arange(16).reshape(4,4)
print(m1)

df1=pd.DataFrame(m1,index=['r1','r2','r3','r4'],columns=['c1','c2','c3','c4'])
df1

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


c1  c2  c3  c4
r1   0   1   2   3
r2   4   5   6   7
r3   8   9  10  11
r4  12  13  14  15

csv file

In [13]:
import pandas as pd
df3=pd.read_csv(r'/Users/new algo trading/batch32/11_data_analysis/sp500.csv')
df3

Name                  Sector   Price    EPS
0                     Apple Inc  Information Technology  170.12   9.20
1                    Abbvie Inc             Health Care   93.29   5.31
2           Abbott Laboratories             Health Care   55.28   2.41
3                 Accenture Plc  Information Technology  145.30   5.91
4                  Allergan Plc             Health Care  171.81  15.42
..                          ...                     ...     ...    ...
97   Verizon Communications Inc      Telecommunications   45.85   3.75
98     Walgreens Boots Alliance        Consumer Staples   70.25   5.10
99        Wells Fargo & Company              Financials   54.02   4.14
100             Wal-Mart Stores        Consumer Staples   96.08   4.36
101            Exxon Mobil Corp                  Energy   80.31   3.56

[102 rows x 4 columns]

exel

In [15]:
!pip3 install openpyxl

  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]1/2 [openpyxl]


In [16]:
import pandas as pd
df5=pd.read_excel(r'/Users/new algo trading/batch32/11_data_analysis/demo1.xlsx')
df5

a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

html

In [18]:
!pip install lxml

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.4/8.4 MB 7.0 MB/s eta 0:00:00a 0:00:01m


In [19]:
df7=pd.read_html('https://en.wikipedia.org/wiki/NIFTY_50')
df7

[                                                    0  \
 0                                                 NaN   
 1   Performance of the NIFTY 50 index between 1990...   
 2                                          Foundation   
 3                                            Operator   
 4                                           Exchanges   
 5                                      Trading symbol   
 6                                        Constituents   
 7                                                Type   
 8                                    Weighting method   
 9                                     Related indices   
 10                                            Website   
 
                                                     1  
 0                                                 NaN  
 1   Performance of the NIFTY 50 index between 1990...  
 2                        22 April 1996 (29 years ago)  
 3                                         NSE Indices  
 4               

In [23]:
df7[1]

Company name      Symbol  \
0                 Adani Enterprises    ADANIENT   
1                 Adani Ports & SEZ  ADANIPORTS   
2                  Apollo Hospitals  APOLLOHOSP   
3                      Asian Paints  ASIANPAINT   
4                         Axis Bank    AXISBANK   
5                        Bajaj Auto  BAJAJ-AUTO   
6                     Bajaj Finance  BAJFINANCE   
7                     Bajaj Finserv  BAJAJFINSV   
8                Bharat Electronics         BEL   
9                     Bharti Airtel  BHARTIARTL   
10                            Cipla       CIPLA   
11                       Coal India   COALINDIA   
12         Dr. Reddy's Laboratories     DRREDDY   
13                    Eicher Motors   EICHERMOT   
14                          Eternal     ETERNAL   
15                Grasim Industries      GRASIM   
16                          HCLTech     HCLTECH   
17                        HDFC Bank    HDFCBANK   
18                        HDFC Life    HDFCLIFE   
19                    Hero MotoCorp  HEROMOTOCO   
20              Hindalco Industries    HINDALCO   
21               Hindustan Unilever  HINDUNILVR   
22                       ICICI Bank   ICICIBANK   
23                    IndusInd Bank  INDUSINDBK   
24                          Infosys        INFY   
25                              ITC         ITC   
26           Jio Financial Services      JIOFIN   
27                        JSW Steel    JSWSTEEL   
28              Kotak Mahindra Bank   KOTAKBANK   
29                  Larsen & Toubro          LT   
30              Mahindra & Mahindra         M&M   
31                    Maruti Suzuki      MARUTI   
32                     Nestlé India   NESTLEIND   
33                             NTPC        NTPC   
34  Oil and Natural Gas Corporation        ONGC   
35                       Power Grid   POWERGRID   
36              Reliance Industries    RELIANCE   
37       SBI Life Insurance Company     SBILIFE   
38                  Shriram Finance  SHRIRAMFIN   
39              State Bank of India        SBIN   
40                       Sun Pharma   SUNPHARMA   
41        Tata Consultancy Services         TCS   
42           Tata Consumer Products  TATACONSUM   
43                      Tata Motors  TATAMOTORS   
44                       Tata Steel   TATASTEEL   
45                    Tech Mahindra       TECHM   
46                    Titan Company       TITAN   
47                            Trent       TRENT   
48                 UltraTech Cement  ULTRACEMCO   
49                            Wipro       WIPRO   

                        Sector[15]        Date added[16]  
0                  Metals & Mining     30 September 2022  
1                         Services     28 September 2015  
2                       Healthcare         31 March 2022  
3                Consumer Durables      27 April 2012[a]  
4               Financial Services         27 March 2009  
5   Automobile and Auto Components     1 October 2010[b]  
6               Financial Services     29 September 2017  
7               Financial Services          2 April 2018  
8                    Capital Goods     30 September 2024  
9                Telecommunication          1 March 2004  
10                      Healthcare        7 October 1998  
11     Oil, Gas & Consumable Fuels       10 October 2011  
12                      Healthcare     1 October 2010[c]  
13  Automobile and Auto Components          1 April 2016  
14               Consumer Services         28 March 2025  
15          Construction Materials       2 April 2018[d]  
16          Information Technology       28 October 2002  
17              Financial Services         22 April 1996  
18              Financial Services          31 July 2020  
19  Automobile and Auto Components     7 October 1998[e]  
20                 Metals & Mining         22 April 1996  
21      Fast Moving Consumer Goods         22 April 1996  
22              Financial Services       25 January 2002  
23   